SPECFILE    = $(shell find -maxdepth 1 -type f -name *.spec)
PACKAGE     = $(shell awk '$$1 == "Name:"     { print $$2 }' $(SPECFILE) )
VERSION     = $(shell awk '$$1 == "Version:"  { print $$2 }' $(SPECFILE) )
RELEASE     = $(shell awk '$$1 == "Release:"  { print $$2 }' $(SPECFILE) )
TARFILE     = $(PACKAGE)-$(VERSION).tar.gz

all:
	tar cvzf $(TARFILE) --exclude-vcs --transform 's,^,$(PACKAGE)-$(VERSION)/,' *

clean:
	rm $(TARFILE)

